# -*- coding: utf-8 -*-
"""p370.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dCPHkL0K1HbZTMVyi_yXd9VK2rUXlPIp
"""

import streamlit as st

import pandas as pd
from pickle import load

def create_page():
    st.title('Customer segmentation')
    st.write('Cluster')
    Education = st.sidebar.slider('Education',min_value=0,max_value=2)
    Age = st.sidebar.slider('Choose your age', min_value=10, max_value=80)
    Children = st.sidebar.slider('Children', min_value=0, max_value=3)
    MaritalStatus = st.sidebar.radio('Marital Status', [0, 1], key='Marital_Status')
    Income = st.slider('Income', min_value=1730, max_value=113734)
    Recency = st.sidebar.slider('Recency', min_value=0, max_value=5)
    Wines = st.sidebar.slider('Wines', min_value=0.0, max_value=8.0, step=0.1)
    Fruits = st.sidebar.slider('Fruits', min_value=0.0, max_value=5.0, step=0.1)
    Meat = st.sidebar.slider('Meat', min_value=0.0, max_value=7.0, step=0.1)
    Fish = st.sidebar.slider('Fish', min_value=0.0, max_value=6.0, step=0.1)
    Sweet = st.sidebar.slider('Sweet', min_value=0.0, max_value=6.0, step=0.1)
    Gold = st.sidebar.slider('Gold', min_value=0, max_value=6,step=1)
    Discount_Purchases = st.sidebar.slider('Discount_Purchases', min_value=0.0, max_value=3.0, step=0.1)
    Web_Purchases = st.sidebar.slider('Web_Purchases', min_value=0.0, max_value=4.0, step=0.1)
    Catalog_Purchases = st.sidebar.slider('Catalog_Purchases', min_value=0.0, max_value=4.0, step=0.1)
    Store_Purchases = st.sidebar.slider('Store_Purchases', min_value=0.0, max_value=4.0, step=0.1)
    NumWebVisitsMonth = st.sidebar.slider('NumWebVisitsMonth', min_value=0.0, max_value=4.0, step=0.1)
    AcceptedCmp1 = st.sidebar.radio('AcceptedCmp1', [0, 1])
    AcceptedCmp2 = st.sidebar.radio('AcceptedCmp2', [0, 1])
    AcceptedCmp3 = st.sidebar.radio('AcceptedCmp3', [0, 1])
    AcceptedCmp4 = st.sidebar.radio('AcceptedCmp4', [0, 1])
    AcceptedCmp5 = st.sidebar.radio('AcceptedCmp5', [0, 1])
    Complain = st.sidebar.slider('Complain', min_value=0.0, max_value=3.0, step=0.1)
    Response = st.sidebar.radio('Response', [0,1], key='Response')

    data1 = {'Education': Education, 'Marital_Status': MaritalStatus, 'Income': Income,
             'Recency': Recency, 'MntWines': Wines, 'MntFruits': Fruits, 'MntMeatProducts': Meat,
             'MntFishProducts': Fish, 'MntSweetProducts': Sweet,'MntGoldProds':Gold,'NumDealsPurchases': Discount_Purchases,
             'NumWebPurchases': Web_Purchases, 'NumCatalogPurchases': Catalog_Purchases,
             'NumStorePurchases': Store_Purchases, 'NumWebVisitsMonth': NumWebVisitsMonth,
             'AcceptedCmp3': AcceptedCmp3, 'AcceptedCmp4': AcceptedCmp4, 'AcceptedCmp5': AcceptedCmp5,
             'AcceptedCmp1': AcceptedCmp1,'AcceptedCmp2': AcceptedCmp2, 'Complain': Complain,'Response':Response,'age': Age,'Children': Children}

    df = pd.DataFrame(data1, index=[0])
    return df
features = create_page()

if st.sidebar.button('Submit'):
    st.write(features)

    loaded_model = load(open('clusf.pkl', 'rb'))
    preds = loaded_model.predict(features)

    st.write(f'Belongs to cluster {preds[0]}')

    st.write(preds)

